apiVersion: v1
kind: ServiceAccount
metadata:
  name: carrier-webhook
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carrier-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - events
    verbs:
      - list
      - watch
      - get
      - create
      - patch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - rolebindings
    verbs:
      - list
      - watch
      - get
      - create
  - apiGroups:
      - "carrier.ocgi.dev"
    resources:
      - "*"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carrier-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carrier-webhook
subjects:
  - kind: ServiceAccount
    name: carrier-webhook
    namespace: kube-system
---
kind: Service
apiVersion: v1
metadata:
  name: carrier-webhook-service
  namespace: kube-system
  labels:
    app: carrier-webhook
spec:
  selector:
    app: carrier-webhook
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrier-webhook
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carrier-webhook
  template:
    metadata:
      labels:
        app: carrier-webhook
    spec:
      serviceAccountName: carrier-webhook
      containers:
        - args:
            - --tlscert=/root/cert.pem
            - --tlskey=/root/key.pem
            - --v=6
            - --port=443
            - --sidecar-image=ocgi/carrier-sdkserver:latest
          image: docker.io/ocgi/carrier-webhook:latest
          imagePullPolicy: Always
          name: webhook
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: wbssecret
      volumes:
        - name: wbssecret
          secret:
            secretName: carrier-wbssecret
            items:
              - key: key.pem
                path: key.pem
              - key: cert.pem
                path: cert.pem