apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: carrier-mutator
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        namespace: kube-system
        name: carrier-webhook-service
        path: /mutate
    failurePolicy: Ignore
    name: carrier-webhook.ocgi.dev
    namespaceSelector:
      matchExpressions:
        - key: ns
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - "carrier.ocgi.dev"
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
        scope: '*'
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - 'pods'
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10